### ISSUE TITLE
default behavior to use the same db details for all inputs

### ISSUE THREAD

**Issue by ryanmerolle** [adambaumeister/netdisco_ansible_inventory#2]
Again, great little script!

It may be good to introduce a default behavior for the script to inherit the db details from keys listed directly under input.  These keys could then be inherited by each input if the same keys are undefined within them.  Example using your provided input:
```
Input:
  # Feel free to specify global db defaults for all inputs here:
  type: psql
  # Database name
  dbname: netdisco
  # Database information
  host: your-netdisco-db-host.org.com
  user: ansible-db-user
  password: ansible-db-password
  # Input name, can be anything
  # Multiple input names can be added whem multiple queries are required, or different grouping.
  # For instance, the below groups by Model, you may want to group by DNS, or site, or some other attributes.
  netdb_switches_by_model:
    # Type
    type: psql
    # Database name
    dbname: netdisco
    # Database information
    host: your-netdisco-db-host.org.com
    user: ansible-db-user
    password: ansible-db-password
    # Query to retrieve information
    # PSQL Objects map fields from sql -> fields in inventory
    select: "SELECT dns,model FROM device
             WHERE model IS NOT NULL AND model != '' AND dns != ''
             AND model NOT LIKE '.%'
             AND last_discover > NOW() - INTERVAL '10 days'
             ORDER BY model;"

    #  Format of ansible group field. Any rows that have identical group_fields are grouped together.
    group_field: '{{ model }}'
    # Field that contains actual host
    host_field: dns
netdb_switches_by_site_name:
    # Database name to use instead of default
    dbname: netdisco1
    # Query to retrieve information
    # PSQL Objects map fields from sql -> fields in inventory
    select: "SELECT dns,site_name FROM device
             WHERE site_name IS NOT NULL AND site_name != '' AND dns != ''
             AND site_name NOT LIKE '.%'
             AND last_discover > NOW() - INTERVAL '10 days'
             ORDER BY site_name;"

    #  Format of ansible group field. Any rows that have identical group_fields are grouped together.
    group_field: '{{ site_name }}'
    # Field that contains actual host
    host_field: dns
  netdb_switches_by_function:
    # Type
    type: psql
    # Database name
    dbname: netdisco4
    # Database information
    host: your-netdisco4-db-host.org.com
    user: ansible-db-user4
    password: ansible-db-password4
    # Query to retrieve information
    # PSQL Objects map fields from sql -> fields in inventory
    select: "SELECT dns,function FROM device
             WHERE function IS NOT NULL AND function != '' AND dns != ''
             AND function NOT LIKE '.%'
             AND last_discover > NOW() - INTERVAL '10 days'
             ORDER BY function;"

    #  Format of ansible group field. Any rows that have identical group_fields are grouped together.
    group_field: '{{ function }}'
    # Field that contains actual host
    host_field: dns

```

After googling a bit, I'm not sure if postgres supports this function could be  further useful that when duplicate db information is recognized, 1 connection to the db could be maintained with queries passed sequentially and stored by the script for parsing/transforming once the db connection closes.

I figured I would share in case you found it useful, but I do not know the ROI for this all.  Frankly it only eliminates duplication of data in a yaml file.  I honestly think that is useful so I can encrypt the same credentials using vault once instead of multiple times.  I'm not sure if my python expertise are currently able to tackle this, but I may try in the future.

**Comment by adambaumeister** [comment]
Added using _use_ syntax. This directive, under Input specification, will inherit all the other settings from the other input declaration by name.

Items that are already present in the inheriting config are not overwritten by this operation. 

_type_  is still required.

An example below where we use the same query twice but differing group_field definitions to group by other columns in SQL.
```
 netdisco_switches_by_model:
    type: psql
    dbname: netdisco
    host: netdisco.spaghetti.com
    user: user
    password: password
    select: "SELECT dns,model,vendor FROM device
             WHERE model IS NOT NULL AND model != '' AND dns != ''
             AND model NOT LIKE '.%'
             AND last_discover > NOW() - INTERVAL '10 days'
             ORDER BY model LIMIT 50"

    group_field: '{{ model }}'
    host_field: dns

  netdisco_switches_by_vendor:
    type: psql
    # 'use' Inherits configuration settings from any other input, by name
    # Inherit all the DB connection settings
    use: netdisco_switches_by_model
    # Override group_field
    group_field: '{{ vendor }}'
```
