### ISSUE TITLE
ansible_host and ansible_host_port optional fields

### ISSUE THREAD

**Issue by ryanmerolle** [adambaumeister/netdisco_ansible_inventory#3]
It might be useful to allow users to specify what fields are associated to ansible_host and ansible_host_ports.

**Comment by ryanmerolle** [comment]
I investigated the data model, and this optional field if not empty in the yaml and if the field in the query is not null or '' would spit out a json similar to below, moving the hosts list to a host dictionary:
```
{"group-1": {"host1":{"ansible_host": "1.1.1.1", "ansible_host_port": "2222"}, "host2", "host3:{"ansible_host": "3.3.3.3"}}
```

**Comment by adambaumeister** [comment]
Added in #6 
This functionality is done by specifying hostvar spec under the input definition.
```
    host_vars:
        # Column from database to retrieve
      - column: vendor
        # Name of hostvar
        var: vendor      
```
Columns must appear in the actual select query to be accessible in hostvars.
