### ISSUE TITLE
argument(s) to output file

### ISSUE THREAD

**Issue by ryanmerolle** [adambaumeister/netdisco_ansible_inventory#4]
It would be useful to pass an argument that outputs to a file in the ../ directory as either an ini, a csv, or yaml.  It really does not matter which or if the user has an option.  It would just be useful for troubleshooting or storing snapshots of the inventory in git.

**Comment by adambaumeister** [comment]
This will be in the next release, using INI as the output format.

The ini formatted file is simply another output definition in the configuration file:
```
# Output types
# By default, all outputs will be run
Output:
  # Identifier, can be anything
  ansible:
    # Type of output
    type: AnsibleJSON
  ansibleini:
    type: AnsibleINI
    # Optional: File specifies an output file 
    # This will write the output to a file instead of to stdout
    file: C:\Temp\ansibleini.txt
```
If the file directive is not specified, then it acts like any other output and dumps to stdout. 

In addition, when running the code, you will be able to specify the output you want to run by name via commandline like so:
```
python nd_inv.py --output ansibleini
```
